### ISSUE TITLE
Drop CSS properties

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/origami-build-tools#190] opened 2015-01-14 13:54 UTC
A recent change to the SCSS compiler drops all the following properties:

```css
background-image: -webkit-gradient(linear, left top, left bottom, from(#549ccf), to(#4781aa));
background-image: -webkit-linear-gradient(top, #549ccf, #4781aa);
background-image: -moz-linear-gradient(top, #549ccf, #4781aa);
background-image: -o-linear-gradient(top, #549ccf, #4781aa);
background-image: -ms-linear-gradient(top, #549ccf, #4781aa);
```

The compiler leaves the following untouched:

```css
background-image: linear-gradient(top, #549ccf, #4781aa);
filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0, StartColorStr=#549ccf,  endColorstr=#4781aa);
```

For this reason, gradient doesn't work anymore in Chrome.

**Comment by kaelig** [comment] 2015-01-14 14:57
Origami encourages usage of a CSS pre-processor or post-processor to prefix properties. We recommend https://github.com/postcss/autoprefixer.

Sorry it is not documented well, maybe we should amend the spec to surface that. Where in the spec would you expect this to be documented?

**Comment by roland-vachter** [comment] 2015-01-14 15:12
What I know is that it worked, and now it doesn't :)
So I didn't start with the expectation to find it in the spec, my point of view is that as it worked before, it's broken that it doesn't work at the moment.

**Comment by kaelig** [comment] 2015-01-14 15:17
Good point. We are trying to get better at informing other developers of these changes, what would you suggest and how would you have liked to be informed of that change?

**Comment by roland-vachter** [comment] 2015-01-14 15:19
Well, it can be considered a breakable change. So maybe increasing a major version would help. Then you know something changed in the API and you should revisit the spec.

**Comment by kaelig** [comment] 2015-01-14 15:27
I am not sure what you mean when you say it is a breaking change. Do you mean that the linter raises warnings?

**Comment by roland-vachter** [comment] 2015-01-14 15:37
No, it's a change that could break existing modules.

**Comment by kaelig** [comment] 2015-01-14 16:57
Oh sorry my bad I think I had misunderstood what you were saying.

It might actually be a bug because `obt build` and `obt demo` are supposed to autoprefix properties for browsers that follow these criteria:

```
['> 1%', 'last 2 versions', 'ie > 6', 'ff ESR']
```

Can you share the steps to reproduce the problem so that we can troubleshoot it?

**Comment by roland-vachter** [comment] 2015-01-15 07:55
Yes, so basically put this into an SCSS file:

```scss
background-image: -webkit-gradient(linear, left top, left bottom, from(#549ccf), to(#4781aa));
background-image: -webkit-linear-gradient(top, #549ccf, #4781aa);
background-image: -moz-linear-gradient(top, #549ccf, #4781aa);
background-image: -o-linear-gradient(top, #549ccf, #4781aa);
background-image: -ms-linear-gradient(top, #549ccf, #4781aa);
background-image: linear-gradient(top, #549ccf, #4781aa);
filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0, StartColorStr=#549ccf,  endColorstr=#4781aa);
```

Build it with OBT, the result is this:

```css
background-image: -ms-linear-gradient(top, #549ccf, #4781aa);
background-image: linear-gradient(top, #549ccf, #4781aa);
filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0, StartColorStr=#549ccf,  endColorstr=#4781aa);
```

The others have disappeared completely, which even if autoprefixer is a good option, valid CSS shouldn't be stripped out.

**Comment by kaelig** [comment] 2015-01-15 09:37
Thanks for the details.

It's a funny coincidence that you opened this issue exactly at the same time Autoprefixer v5 was released: https://github.com/postcss/autoprefixer/releases/tag/5.0.0. Not sure it's linked though.

Looks like adding `remove:false` to the config (in both demo.js and build.js) should fix your issue by preventing autoprefixer from removing prefixed properties it deems are outdated. Do you want to give it a go?

**Comment by kaelig** [comment] 2015-01-15 09:46
Also, I may have found why the webkit prefixes have disappeared.

Support for CSS gradients in Chrome mobile (the small yellow text means it's supported with prefixes):
![screenshot 2015-01-15 09 38 26](https://cloud.githubusercontent.com/assets/85783/5755260/4ec72b4c-9c9a-11e4-8b12-87b0799cc1ef.png)

We tell the autoprefixer to output prefixes for the two last versions of a browser. But since Android Browser 4.4 apparently went up directly from "4.4.4" to "37" (Chrome)… it probably ended up removing support on versions <= 35.

Another way to solve the problem would then to tell autoprefixer to support all Android browsers > 2.3 (for example).

**Comment by roland-vachter** [comment] 2015-01-15 09:50
Well, I'm on Chrome 39 (latest) and the gradients doesn't work without the prefix.
remove: false sounds good, should it be set by myself or OBT?

**Comment by roland-vachter** [comment] 2015-01-15 09:58
I think the syntax I'm using is a bit outdated, I will try to play with it a bit.

**Comment by roland-vachter** [comment] 2015-01-15 10:02
Fixed the syntax, it works now. Although, in my opinion this doesn't mean that it should stop you from using prefixed properties.
In my case I also have to override third party CSS styles (livefyre), and they are still using all prefixes.

**Comment by kaelig** [comment] 2015-01-15 12:12
Oh, so it was a syntax problem.

To be honest I'm not sure we have changed anything in our code, so maybe the browser stats have evolved recently and autoprefixer would have adapted the code accordingly?

Also: you might want to provide a fallback background color for browsers that don't have support linear gradient, for example:

```css
el {
  background-color: #4781aa;
  background-image: linear-gradient(to bottom, #549ccf, #4781aa);
}
```

I think it's safe to add `remove: false` in the options of OBT. Can you add it, test if that works better for you and then open a pull request?

**Comment by roland-vachter** [comment] 2015-01-15 12:30
So where should I put that remove:false exactly?

**Comment by kaelig** [comment] 2015-01-15 13:40
> in both demo.js and build.js)

https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/demo.js#L43

https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/build.js#L86

**Comment by roland-vachter** [comment] 2015-01-15 13:55
remove: false work fine.

**Comment by roland-vachter** [comment] 2015-01-15 13:57
Could you please do the change? I don't have the OBT set up for dev.

**Comment by kaelig** [comment] 2015-01-15 14:03
I'll add it, and we also need to change the support directives.

Can you try to fiddle around with the configuration (see below)?

```
['> 1%', 'last 2 versions', 'ie > 6', 'ff ESR']
```

Ideally I believe we could support Android 2.3 and up.

Then you'll just need to write:

```
background-image: linear-gradient(to bottom, #549ccf, #4781aa);
```

And autoprefixer will take care of adding the prefixed versions for you.

**Comment by kaelig** [comment] 2015-01-15 16:13
I couldn't reproduce the issue, can you give more context?

Feel free to disable autoprefixer in parts of the code using this technique: https://github.com/postcss/autoprefixer#disabling.

**Comment by roland-vachter** [comment] 2015-01-16 08:47
Did you copy my original CSS? The problem probably was an old syntax of linear-gradient, which is not supported anymore.
Remove: false in OBT and correcting the syntax fixed my problem.

**Comment by kaelig** [comment] 2015-01-16 11:40
I did copy the original CSS and couldn't reproduce what's described in the original issue.

**Comment by AlbertoElias** [comment] 2015-01-21 16:01
Can this be closed then?

**Comment by triblondon** [comment] 2015-01-22 12:12
@roland-vachter we'd like people to use the tools as designed, and so it's a bit disappointing if your ultimate solution is to add your own prefixes.  We'd be very happy to tweak the config of autoprefixer to ensure that it covers any cases we've missed, if you could tell us what they are.

You can also override our autoprefixer config, which would probably still be a better solution than writing your own prefixes.  Just trying to ensure that the code is as maintainable as possible.

Anyway if you can give us more info we can improve the tools.

**Comment by roland-vachter** [comment] 2015-01-22 12:27
Well, I was not aware that autoprefixer is in place with the OBT. That could be my fault not observing it, or the documentation could just explicitly mention which helper tools are used in order to make awareness.

It works now as it is, so yes, it can be closed, problem solved. Thank you

**Comment by AlbertoElias** [comment] 2015-01-22 12:35
Ok, thank you @roland-vachter, I'll close it

**Closed by AlbertoElias** 2015-01-22 12:35 UTC
